---
title: "drake_graphing_basics"
drake_cache: ".graphingBasics"
output: html_document
---

```{r setup, include=FALSE}
# Google提供的字形
font_families_google() %>%
  stringr::str_subset(regex("noto", ignore_case = T)) # 鎖定東方語系字形系列Noto
font_add_google("Noto Sans TC") # 加入無襯字的Noto繁體中文
font_families() # 查看notoSansTC family有沒有成功加入
```

```{r makecondition}
library(readr)
library(ggplot2)
library(drake)
library(rmd2drake)
library(dplyr)
library(showtext)
library(stringr)
showtext_auto()
theme(
  text=element_text(family = "Noto Sans TC")
  ) %>%
  theme_set()

rprojroot::is_rstudio_project -> pj
pj$make_fix_file() -> root
```

## data

```{r datadownload}
income <- fromJSON("https://quality.data.gov.tw/dq_download_json.php?nid=44218&md5_url=5108938196a413ee42cca40b2e599084")
```


## graph

```{r myggplot}
myggplot = {
  canvas ={
    ggplot()
  }
}
```

```{r subset_of_income}


{
  income$Item_VALUE <- as.integer(income$Item_VALUE) 

  pick <- income$Item == "國內生產毛額GDP(名目值，百萬元)" & income$TYPE == "原始值"

  Item_VALUE <- income$Item_VALUE[pick]

  TIME_PERIOD <- income$TIME_PERIOD[pick]

  subset_of_income <- data.frame(
    `年` = TIME_PERIOD ,
    `國內生產毛額GDP(名目值，百萬元)` = Item_VALUE
    )
  
}
```

```{r ggpath}
ggpath <- {
  myggplot +
    geom_point(
      mapping =  aes(x = `年`, y = `國內生產毛額GDP.名目值.百萬元.`  ),
      subset_of_income
    )
}
```

```{r}

```

```{r}

```

```{r}

```


## export

```{r save_ggplot}
save_ggplot = {

  ggsave(
    plot=ggpath,
    filename=file.path(imageFolder, "myPlot.svg"),
    width = 8,
    height = 5
  )
}
```

  * myPlot.svg及本Rmd檔一起上傳作業繳交處
