---
title: "????????????循環"
drake_cache: ".chart1_sunny" # 請???????????????為幾????????????人???????????????cache???稱
output: html_document
params:
  key: "???Aa-???-1" # 課綱編?????????個可??? ["key1", "key2"]
  memberNames: ["Mary", "cook"] # 組員姓???
  memberIds: ["410888292", "410772938"] # 學???
  imgPreName: "taiwanEconomicsGrowth.svg" # ggsave????????????
  imgPostName: "" # svg後製????????????
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, drake=F}
knitr::opts_chunk$set(echo = TRUE, eval=F)
library(drake)
library(econDV)
library(dplyr)

```

## makecondition

```{r makecondition}
library(dplyr)
library(tidyr)
library(stringr)
library(googledrive)
library(readr)
library(ggmap)
library(osmdata)
library(ggplot2)
library(econDV)
library(sf)
library(tibble)

font_families_google() %>%
  stringr::str_subset(regex("noto", ignore_case = T))  
font_add_google("Noto Sans TC") 

rprojroot::is_rstudio_project -> .pj
.pj$make_fix_file() -> .root

imageFolder <- file.path(.root(),"img")
dataFolder <- file.path(.root(),"data")

if(!dir.exists(imageFolder)) dir.create(imageFolder)
if(!dir.exists(dataFolder)) dir.create(dataFolder)

xfun::download_file("https://www.dropbox.com/s/7b3nbgfx5bgft8g/drake_annotationmaps.Rdata?dl=1")
load("C:/Users/tonyf/Desktop/drake_annotationmaps.Rdata")

stringr::str_replace(
drake$process2get$storr_rdsOptions,
"(?<=(storr_rds\\())[\"[:graph:]]+(?=,)",
'file.path(.root(),".map")'
) -> drake$process2get$storr_rdsOptions
drake$activeRmd$frontmatter$drake_cache <- file.path(.root(),".map")

xfun::download_file("https://www.dropbox.com/s/8ndtvzqbdb4cb93/data_visulaization_pk.R?dl=1")
source("data_visulaization_pk.R", encoding = "UTF-8")


register_google( key = "AIzaSyBA0wN6WtykE00RN1bMMv0P9YPNIVgtR3U" , write = TRUE )

```

```{r}
dsf_taiwan <- 
  sf::read_sf("C:/Users/tonyf/Documents/GitHub/109-1-econDV/drake/???增??????夾")
```

```{r}
dsf_taiwan %>%
  ggplot() +
  geom_sf()
```

---
```{r}
dsf_taiwan %>%
  rmapshaper::ms_simplify() -> dsf_taiwan_simplify
```

```{r}
dsf_taiwan_simplify %>%
  ggplot()+geom_sf()
```

```{r}
dsf_taiwan_simplify %>%
  st_crop(c(xmin=119,xmax=122,ymin=22,ymax=25.8)) -> dsf_taiwanCropped
```

```{r}
dsf_taiwanCropped %>%
  ggplot()+geom_sf()
```

---

```{r}
library("osmdata")
```

```{r}
osmdata::getbb("new taipei") -> newTaipeiBBox
newTaipeiBBox
```

```{r}
stringr::str_subset(osmdata::available_features(), "boundary|admin")
```


```{r}
osmdata::getbb("new taipei") -> newTaipeiBBox
dsf_newTaipei <- opq(newTaipeiBBox) %>% 
     add_osm_feature(key="admin_level", value="5") %>%
     osmdata::osmdata_sf()
```

```{r}
dsf_newTaipei$osm_lines %>%
  ggplot()+geom_sf()
```

```{r}
dsf_newTaipei$osm_multipolygons %>%
  osm_geom_rename() %>%
  dplyr::filter(stringr::str_detect(name, "峽|???|???")
  ) %>%
  ggplot()+geom_sf()
```

```{r}
dsf_newTaipei$osm_multipolygons %>%
  osm_geom_rename() %>% # 多???這??????
  ggplot()+
  geom_sf(
    aes(fill=name),
    color="white", size=0.2
  )+
  colorspace::scale_fill_discrete_qualitative()+
  theme_void()
```









